spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/users-db?createDatabaseIfNotExist=true
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  port: 9093

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

rsa:
  publicKey: classpath:/certs/public.pem
  privateKey: classpath:/certs/private.pem

logging:
  level:
    org:
      springframework:
        security: DEBUG

